// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/styles.css.ts";
import * as $$0 from "./islands/AddToCartButton.tsx";
import * as $$1 from "./islands/HeaderButton.tsx";
import * as $$2 from "./islands/HeaderModals.tsx";
import * as $$3 from "./islands/HeaderSearchbar.tsx";
import * as $$4 from "./islands/Newsletter.tsx";
import * as $$5 from "./islands/OutOfStock.tsx";
import * as $$6 from "./islands/ProductImageZoom.tsx";
import * as $$7 from "./islands/SearchControls.tsx";
import * as $$8 from "./islands/ShippingSimulation.tsx";
import * as $$9 from "./islands/SliderJS.tsx";
import * as $$10 from "./islands/WishlistButton.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/styles.css.ts": $1,
  },
  islands: {
    "./islands/AddToCartButton.tsx": $$0,
    "./islands/HeaderButton.tsx": $$1,
    "./islands/HeaderModals.tsx": $$2,
    "./islands/HeaderSearchbar.tsx": $$3,
    "./islands/Newsletter.tsx": $$4,
    "./islands/OutOfStock.tsx": $$5,
    "./islands/ProductImageZoom.tsx": $$6,
    "./islands/SearchControls.tsx": $$7,
    "./islands/ShippingSimulation.tsx": $$8,
    "./islands/SliderJS.tsx": $$9,
    "./islands/WishlistButton.tsx": $$10,
  },
  baseUrl: import.meta.url,
};

export default manifest;
